export const genres = [
  { value: "All", label: "Todas" },
  { value: "Desarrollo Personal", label: "Desarrollo Personal" },
  { value: "Autoayuda", label: "Autoayuda" },
  { value: "Negocios", label: "Negocios" },
  { value: "Espiritualidad", label: "Espiritualidad" },
  { value: "Motivación", label: "Motivación" },
  { value: "Productividad", label: "Productividad" },
  { value: "Ciencia Ficción", label: "Ciencia Ficción" },
  { value: "Filosofía", label: "Filosofía" },
  { value: "Psicología", label: "Psicología" },
  { value: "Educación", label: "Educación" },
  { value: "Finanzas", label: "Finanzas" },
  { value: "Terapias alternativas", label: "Terapias alternativas" },
  { value: "Ventas", label: "Ventas" },
  { value: "Sociedad", label: "Sociedad" },
  { value: "Economía", label: "Economía" },
  { value: "Política", label: "Política" },
  { value: "Relaciones", label: "Relaciones" },
  { value: "Salud", label: "Salud" },
];